### ISSUE TITLE
Follow best performance practice

### ISSUE THREAD

**Issue by onlinebizsoft** [barthy-koeln/scroll-snap-slider#21]
For autoplay implementation, I think we should use requestanimationframe (and requestidlecallback) instead of using interval which block the browser paint.

**Comment by barthy-koeln** [comment]
Hi,

thanks for the feedback. You're right, `offsetWidth` and `scrollWidth` force a reflow, as well as using `scrollTo` and `scrollBy`. I will implement the animation frame to to these things.

However, I will keep the intervals, since this library doesn't animate anything by itself. It doesn't need an animation loop, it just needs to trigger browser native scroll functions. Some of the calculations should be better timed though, so a pull request is incoming.

Do you currently have a test setup where you would be able to confirm performance improvements?

**Comment by onlinebizsoft** [comment]
@barthy-koeln sorry, I don't have any demo which currently show a performance issue with the slider (because other things might be ahead of this issue so I will get back when it is visible on the metric)

**Comment by barthy-koeln** [comment]
Hey @onlinebizsoft :)

If you like, check out the branch `fix/layout-thrashing`.

The only real improvement I have been able to see was this stat:

Before (`main`):
![Screenshot from 2023-07-01 17-26-42](https://github.com/barthy-koeln/scroll-snap-slider/assets/10552683/ee0b8332-7e16-4d63-a704-7f1b3344f2e1)

After (`fix/layout-thrashing`):
![Screenshot from 2023-07-01 17-27-41](https://github.com/barthy-koeln/scroll-snap-slider/assets/10552683/e271a514-350b-4298-a5b7-bd19bd7b135b)

Slightly higher heap size, but quite some fewer style recalculations.

The test setup can be found in `demo/test.html`. It contains 64 sliders with 10 images each, all visible at once.

 If you want to compare it to `main`, just check out that test there:

`git checkout fix/layout-thrashing -- demo/test.html`

**Comment by onlinebizsoft** [comment]
Did you push the branch? I only see "main" branch

**Comment by barthy-koeln** [comment]
I did now, looks like weekend-brain had already kicked in :)
